name: Prepare
description: Common prepare steps
inputs:
  keystore:
    description: The KEYSTORE secret
    required: true
  gradle-properties:
    description: The GRADLE_PROPERTIES secret
    required: true
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup the JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17

    - name: Setup cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          build
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Setup the secrets
      shell: bash
      run: |
        mkdir -p $HOME/.gradle
        echo "$INPUT_KEYSTORE" | base64 -d > $HOME/.gradle/keystore.jks
        echo "$INPUT_GRADLE_PROPERTIES" | base64 -d | sed "s:\$HOME:$HOME:g" > $HOME/.gradle/gradle.properties
