on:
  workflow_call:
    outputs:
      last-changelog:
        value: ${{ jobs.update-changelogs.outputs.last-changelog }}
    secrets:
      KEYSTORE:
        required: true
      GRADLE_PROPERTIES:
        required: true
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Prepare
        uses: necauqua/mcmod-workflow/.github/actions/prepare@main
        with:
          keystore: ${{ secrets.KEYSTORE }}
          gradle-properties: ${{ secrets.GRADLE_PROPERTIES }}

      - name: Build and test
        run: ./gradlew build test

      - name: Short commit SHA
        id: short-sha
        run: echo short-sha=${GITHUB_SHA::7} >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        if: ${{ runner.os == 'Linux' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-build-${{ steps.short-sha.outputs.short-sha }}.zip
          path: build/libs/

  update-changelogs:
    name: Update changelogs
    needs: [build] # run after build/test so that if it fails we don't update stuff just yet
    runs-on: ubuntu-latest
    outputs:
      last-changelog: ${{ steps.last-changelog.outputs.last-changelog }}

    steps:
      - name: Checkout the main repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout the wiki
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}.wiki
          path: wiki

      - name: Extract changelog
        uses: necauqua/changelogs/extract@v1

      - name: Render changelog
        uses: necauqua/changelogs/render@v1
        with:
          date-format: 1%F
          filename: wiki/Changelog.md
          template: .github/workflows/changelog-template.md

      - name: Render last changelog
        id: last-changelog
        uses: necauqua/changelogs/render@v1
        with:
          filename: last-changelog.md
          only-last: true

      - name: Store last changelog
        run: |
          echo last-changelog="$(cat last-changelog.md | base64)" >> $GITHUB_OUTPUT

      - name: Generate Forge updates.json
        uses: necauqua/changelogs/gen-forge-updates@v1
        with:
          filename: wiki/updates.json
          template: .github/workflows/updates-template.json

      - name: Push to wiki
        run: |
          cd wiki
          git config --local user.email action@github.com
          git config --local user.name 'Changelog Updater'
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m 'Update changelog'
          git push
